"""
BeHive Model Configuration — per-stage model routing.

Allows users to assign different LLM models to different pipeline stages:
- scout: query generation, source discovery (cheap, fast)
- harvest: content analysis, relevance scoring (cheap, fast)
- process: claim extraction, quality scoring (medium)
- synth: report synthesis, cross-referencing (expensive, smart)

Config stored in ~/.behive/config.yaml

Usage:
    behive config --quick    # one model for everything
    behive config --full     # pick model per stage
    behive config --show     # display current config
"""

import os
import sys
from pathlib import Path
from typing import Optional

# ─── Defaults ─────────────────────────────────────────────────────────────────

CONFIG_DIR = Path(os.environ.get("BEHIVE_CONFIG_DIR", Path.home() / ".behive"))
CONFIG_FILE = CONFIG_DIR / "config.yaml"

# Pipeline stages and their roles
STAGES = {
    "scout": {
        "description": "Source discovery & query generation",
        "role": "Fast, cheap — generates search queries and scores URL relevance",
        "default": "claude-haiku",
    },
    "harvest": {
        "description": "Content extraction & relevance filtering",
        "role": "Fast, cheap — filters irrelevant content, detects language",
        "default": "claude-haiku",
    },
    "process": {
        "description": "Claim extraction & quality scoring",
        "role": "Medium — extracts structured claims from text, scores quality",
        "default": "claude-haiku",
    },
    "synth": {
        "description": "Report synthesis & cross-referencing",
        "role": "Smart, thorough — synthesizes final report, deduplicates, verifies",
        "default": "claude-sonnet",
    },
}

# Known model presets (user can also pass any litellm-compatible model string)
MODEL_PRESETS = {
    # Anthropic
    "claude-haiku": "anthropic/claude-haiku-4-5-20251001",
    "claude-sonnet": "anthropic/claude-sonnet-4-20250514",
    "claude-opus": "anthropic/claude-opus-4-20250514",
    # OpenAI
    "gpt-4o-mini": "openai/gpt-4o-mini",
    "gpt-4o": "openai/gpt-4o",
    "gpt-4.1-mini": "openai/gpt-4.1-mini",
    "gpt-4.1": "openai/gpt-4.1",
    # AWS Bedrock
    "bedrock-haiku": "bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0",
    "bedrock-sonnet": "bedrock/us.anthropic.claude-sonnet-4-6-v1@us-east-1",
    "bedrock-opus": "bedrock/us.anthropic.claude-opus-4-6-v1@us-east-1",
    # Google
    "gemini-flash": "google/gemini-2.5-flash",
    "gemini-pro": "google/gemini-2.5-pro",
    # Local (user must have server running)
    "local": "openai/local-model",
    "ollama": "ollama/llama3.1",
}

# Recommended combos
RECOMMENDED_COMBOS = {
    "budget": {
        "description": "Cheapest — Haiku/GPT-4o-mini everywhere (~$0.30/mission)",
        "scout": "claude-haiku",
        "harvest": "claude-haiku",
        "process": "claude-haiku",
        "synth": "claude-haiku",
    },
    "balanced": {
        "description": "Best value — cheap collection, smart synthesis (~$1.50/mission)",
        "scout": "claude-haiku",
        "harvest": "claude-haiku",
        "process": "claude-haiku",
        "synth": "claude-sonnet",
    },
    "quality": {
        "description": "Maximum quality — Sonnet everywhere (~$4.00/mission)",
        "scout": "claude-sonnet",
        "harvest": "claude-haiku",
        "process": "claude-sonnet",
        "synth": "claude-sonnet",
    },
    "local": {
        "description": "Fully local — requires running LLM server ($0.00/mission)",
        "scout": "local",
        "harvest": "local",
        "process": "local",
        "synth": "local",
    },
}


# ─── Config Management ────────────────────────────────────────────────────────

def load_config() -> dict:
    """Load config from ~/.behive/config.yaml or return defaults."""
    if CONFIG_FILE.exists():
        try:
            import yaml
            with open(CONFIG_FILE) as f:
                cfg = yaml.safe_load(f) or {}
            return cfg
        except ImportError:
            # Fallback: simple key=value parsing
            cfg = {}
            for line in CONFIG_FILE.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith("#") and ":" in line:
                    k, v = line.split(":", 1)
                    cfg[k.strip()] = v.strip()
            return cfg
    return {}


def save_config(cfg: dict):
    """Save config to ~/.behive/config.yaml."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    try:
        import yaml
        with open(CONFIG_FILE, "w") as f:
            yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
    except ImportError:
        # Fallback: manual YAML-like format
        lines = ["# BeHive Configuration\n", "# Generated by: behive config\n\n"]
        for k, v in cfg.items():
            if isinstance(v, dict):
                lines.append(f"{k}:\n")
                for sk, sv in v.items():
                    lines.append(f"  {sk}: {sv}\n")
            else:
                lines.append(f"{k}: {v}\n")
        CONFIG_FILE.write_text("".join(lines))


def get_model_for_stage(stage: str) -> str:
    """Get the configured model for a pipeline stage.
    
    Priority (highest wins):
    1. BEHIVE_MODEL_{STAGE} env var
    2. BEHIVE_MODEL env var (global)
    3. config.yaml stage-specific
    4. config.yaml default
    5. hardcoded default
    """
    # Env var per-stage (highest priority — useful for Docker/CI overrides)
    env_stage = os.environ.get(f"BEHIVE_MODEL_{stage.upper()}")
    if env_stage:
        return MODEL_PRESETS.get(env_stage, env_stage)
    
    # Env var global
    env_global = os.environ.get("BEHIVE_MODEL")
    if env_global:
        return MODEL_PRESETS.get(env_global, env_global)
    
    # Config file
    cfg = load_config()
    models = cfg.get("models", {})
    
    # Stage-specific from config
    model_name = models.get(stage)
    if model_name:
        return MODEL_PRESETS.get(model_name, model_name)
    
    # Global from config
    model_name = models.get("default")
    if model_name:
        return MODEL_PRESETS.get(model_name, model_name)
    
    # Hardcoded default
    model_name = STAGES[stage]["default"]
    return MODEL_PRESETS.get(model_name, model_name)


def get_all_stage_models() -> dict:
    """Get model assignments for all stages."""
    return {stage: get_model_for_stage(stage) for stage in STAGES}


# ─── Interactive Config ───────────────────────────────────────────────────────

def run_quick_config():
    """Quick config — one model for everything."""
    print("\n🐝 BeHive Quick Config")
    print("=" * 50)
    print("\nChoose a model for all pipeline stages:\n")
    
    presets = list(MODEL_PRESETS.keys())
    for i, name in enumerate(presets, 1):
        marker = "⭐" if name == "claude-haiku" else "  "
        print(f"  {marker} {i:2d}. {name:20s} → {MODEL_PRESETS[name]}")
    
    print(f"\n  Or type any litellm-compatible model string (e.g. 'ollama/mistral')")
    print(f"\n  Recommended combos:")
    for name, combo in RECOMMENDED_COMBOS.items():
        print(f"    [{name}] {combo['description']}")
    
    choice = input(f"\nModel or combo name [balanced]: ").strip() or "balanced"
    
    if choice in RECOMMENDED_COMBOS:
        combo = RECOMMENDED_COMBOS[choice]
        cfg = load_config()
        cfg["models"] = {stage: combo[stage] for stage in STAGES}
        save_config(cfg)
        print(f"\n✅ Applied '{choice}' preset:")
        for stage in STAGES:
            resolved = MODEL_PRESETS.get(combo[stage], combo[stage])
            print(f"   {stage:10s} → {resolved}")
    elif choice.isdigit() and 1 <= int(choice) <= len(presets):
        model_name = presets[int(choice) - 1]
        cfg = load_config()
        cfg["models"] = {"default": model_name}
        save_config(cfg)
        resolved = MODEL_PRESETS.get(model_name, model_name)
        print(f"\n✅ All stages → {resolved}")
    else:
        # Treat as model string or preset name
        model_name = choice
        cfg = load_config()
        cfg["models"] = {"default": model_name}
        save_config(cfg)
        resolved = MODEL_PRESETS.get(model_name, model_name)
        print(f"\n✅ All stages → {resolved}")
    
    print(f"\n   Config saved: {CONFIG_FILE}")
    print(f"   Run 'behive config --show' to verify.\n")


def run_full_config():
    """Full config — pick model per stage."""
    print("\n🐝 BeHive Full Config — Model per Stage")
    print("=" * 50)
    print("\nPipeline stages (data flows top to bottom):\n")
    
    for stage, info in STAGES.items():
        print(f"  [{stage:8s}] {info['description']}")
        print(f"             {info['role']}")
        print()
    
    print("Available models:")
    presets = list(MODEL_PRESETS.keys())
    for i, name in enumerate(presets, 1):
        print(f"  {i:2d}. {name:20s} → {MODEL_PRESETS[name]}")
    
    print(f"\n  Or type any litellm model string. Press Enter for default.\n")
    
    cfg = load_config()
    models = {}
    
    for stage, info in STAGES.items():
        default = info["default"]
        choice = input(f"  {stage:8s} [{default}]: ").strip()
        
        if not choice:
            models[stage] = default
        elif choice.isdigit() and 1 <= int(choice) <= len(presets):
            models[stage] = presets[int(choice) - 1]
        else:
            models[stage] = choice
    
    cfg["models"] = models
    save_config(cfg)
    
    print(f"\n✅ Config saved:")
    for stage, model in models.items():
        resolved = MODEL_PRESETS.get(model, model)
        print(f"   {stage:10s} → {resolved}")
    print(f"\n   File: {CONFIG_FILE}")
    print(f"   Run 'behive config --show' to verify.\n")


def show_config():
    """Show current configuration."""
    print("\n🐝 BeHive Current Config")
    print("=" * 50)
    
    if not CONFIG_FILE.exists():
        print(f"\n  No config file found ({CONFIG_FILE})")
        print(f"  Using defaults. Run 'behive config --quick' to set up.\n")
    else:
        print(f"\n  Config: {CONFIG_FILE}\n")
    
    print("  Stage        Model                                      Source")
    print("  " + "─" * 70)
    
    cfg = load_config()
    models = cfg.get("models", {})
    
    for stage in STAGES:
        resolved = get_model_for_stage(stage)
        
        # Determine source
        if stage in models:
            source = "config (stage)"
        elif "default" in models:
            source = "config (global)"
        elif os.environ.get(f"BEHIVE_MODEL_{stage.upper()}"):
            source = "env var"
        elif os.environ.get("BEHIVE_MODEL"):
            source = "env var (global)"
        else:
            source = "default"
        
        print(f"  {stage:10s}   {resolved:42s} {source}")
    
    # Also show env vars if set
    env_models = {k: v for k, v in os.environ.items() if k.startswith("BEHIVE_MODEL")}
    if env_models:
        print(f"\n  Environment overrides:")
        for k, v in env_models.items():
            print(f"    {k}={v}")
    
    print()
